[package]
name = "fido-hid-tester"
version = "0.1.0"
edition = "2021"
authors = ["Michael Farrell <micolous+git@gmail.com>"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.4.2"
rand = "0.8.5"
